name: ViralRiver

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.10

  - fastp
  - kraken2
  - krakentools
  - bwa
  - minimap2
  - bowtie2
  - samtools
  - megahit
  - seqkit
  - blast
  - sra-tools

  - biopython
  - pigz
  - wget
